---
title: "CCLE_All_RNASubset"
author: "Aurora S Blucher"
date: "4/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(here)
library(msigdbr)
```

## CCLE Training -  All; Subset RNA expression matrix to our RSR genes of interest

For the CCLE Training set, subset RNA data to just our lines of interest, genes of interest

Genes - across McGrail RSR, McGrail PARPness, and GSVA Hallmarks 

04/27/21  - Script set up, move section from previous scripts; write to file

```{r}
#CCLE TRAINING SET, read in merged brca/ov/end/panc with all other diseases
training_all<-read_tsv(here("data", "CCLE_Training", "DepMap_forRepStress_AllDiseases_TRAINING_210427.tsv"))

#CCLE RNASeq data
#go back to our full CCLE file
DepMap_RNASeq<-read_csv(here("data", "DepMapCCLE_data", "CCLE_expression.csv"))
#View(DepMap_RNASeq)

#Filter RNASeq data down to our cell lines; 
#cell lines
DepMap_TrainingLines_RNASeq_All<-DepMap_RNASeq %>%
  pivot_longer(-X1, names_to = "Gene", values_to = "Log2_TPM") %>%
  dplyr::select(DepMap_ID = X1, Gene, Log2_TPM) %>%
  filter(DepMap_ID %in% training_all$DepMapID) %>% #need to use DepMapID across data types
  separate(Gene, c("Name", "ID_ToClean"), " ") %>%
  mutate(ID = str_sub(ID_ToClean, 2, -2)) %>%#start at second char, end on 2nd to last chat -> remove "()"
  dplyr::select(DepMap_ID, Gene= Name, Gene_ID = ID, Log2_TPM)
dim(DepMap_TrainingLines_RNASeq_All) #20371284 x 4
#View(DepMap_TrainingLines_RNASeq)
#intermediate, output to file
write_tsv(DepMap_TrainingLines_RNASeq_All, here("data_intermediate", "CCLE_DepMap_expression", "CCLEDepMap_TrainingLines_All_RNASeq_LONG.tsv"))

#Read in for our signatures
#McGrail RSR
#McGrail RSR Genes and Coefficients
RSRSignatureGenes<-read_tsv(here("data","RNA_Signatures", "McGrailRSR_Genes_Coefficients.tsv")) 
View(RSRSignatureGenes)

#McGrail PARPness
PARPnessSignatureGenes<-read_tsv(here("data","RNA_Signatures", "McGrailPARPness_Genes_Coefficients.tsv")) 
View(PARPnessSignatureGenes)

#GSVA hallmarks
hallmark_GeneSets<-msigdbr(species = "Homo sapiens", category = "H")

#rep stress hallmarks of interest*
repStress_hallmarks<-as.data.frame(c("HALLMARK_G2M_CHECKPOINT", "HALLMARK_OXIDATIVE_PHOSPHORYLATION",
                       "HALLMARK_E2F_TARGETS", "HALLMARK_DNA_REPAIR", 
                       "HALLMARK_MYC_TARGETS_V1", "HALLMARK_MYC_TARGETS_V2"))
colnames(repStress_hallmarks)<-c("Hallmark")
#View(repStress_hallmarks)

hallMarkGenes<-hallmark_GeneSets%>%
  filter(gs_name %in% repStress_hallmarks$Hallmark) %>%
  select(Gene = gene_symbol) %>%
  unique()
View(hallMarkGenes) #829 total genes

#COLLECT ALL RSR GENES OF INTEREST ACROSS OUR SETS

#get gene list across these signatures -> merge all 3 here
RSRGenes<-as.data.frame(RSRSignatureGenes$Gene)
colnames(RSRGenes)<-c("Gene")
PARPGenes<-as.data.frame(PARPnessSignatureGenes$Gene)
colnames(PARPGenes)<-c("Gene")
View(RSRGenes)
View(PARPGenes)

merge_signatures<-rbind(RSRGenes, PARPGenes)
merge_sig_gsva<-rbind(merge_signatures, hallMarkGenes)
View(merge_sig_gsva)

merge_sig_gsva_unique<-merge_sig_gsva %>%
  arrange(Gene)%>%
  unique()
View(merge_sig_gsva_unique) #1652 total genes
#output -> Alfonso needs these files for mining in perturbation sets
#and for comparison to CPPA
write_tsv(merge_sig_gsva_unique, here("data_intermediate", "Signatures", "RSRPARPness_GenesOfInterest.tsv"))
```

```{r}

#subset expression matrix to just these genes
#now need to clean the Gene field and filter to our genes
DepMap_RNASeq_RSRGenes<-DepMap_TrainingLines_RNASeq_All %>%
 filter( Gene %in% merge_sig_gsva_unique$Gene) 
dim(DepMap_RNASeq_RSRGenes)
View(unique(DepMap_RNASeq_RSRGenes$Gene)) #1500 genes found in CCLE RNA data
#View(DepMap_RNASeq_RSRGenes)

#output to file
#read in -> CCLE_All_RunSignatures.Rmd


```
