---
title: "MinePerturbedDatasets"
author: "Aurora S Blucher"
date: "5/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(here)
library(tidyverse)

```

## Mining Perturbed Datasets for RSR Signatures

R markdown for mining perturbed RNA data; collaborators' data. 


Using McGrail RSR, McGrail PARPness, and GSVA Hallmarks() of interest

```{r}
#collaborator dataset = PANGEA
#diff expression calls
PANGEA_de<-read_csv(here("data", "Alfonso_PANGEA", "Expression_Gene_query_output.csv"))
View(PANGEA_de)
```

```{r}
#subset to just genes that are in our our list
RSRgenes<-read_tsv(here("data_intermediate", "Signatures", "RSRPARPness_GenesOfInterest.tsv"))
View(RSRgenes) #1652 total RSR genes across our sets


#PANGEA de all
PANGEA_all<-read_csv(here("data", "Alfonso_PANGEA", "PANGEA-diff-expression.csv"))
View(head(PANGEA_all))

Cell_line<-c("aspc", "bt20", "du145", "efo21", "h1793", "hcc1143", "hf2597", "hsts", 
             "krj1", "Incap", "panc1", "tcc", "u87")
Cell_line<-as.data.frame(Cell_line)
colnames(Cell_line)<-c("Name")

PANGEA_observations<-as.data.frame(t(PANGEA_all[1, ])) %>%
  rownames_to_column(var = "Observation_Full") %>%
  select(-V1) %>% #remove
  separate(Observation_Full, sep = "_", into = c("Drug", "Dose", "Time", "Cell_Line"),
           remove = FALSE) %>%
  filter(Cell_Line %in% Cell_line$Name)
View(PANGEA_observations) #4104 observations

#check with alfonso's parsing/ quereying -> make sure this was handled okay
#okay this is annoying, there are _ in some of the drug names, so we will need to fix that
#for now we just exclude those

#now split 80/20
PANGEA_observations_training<-PANGEA_observations %>%
  group_by(Cell_Line) %>%
  sample_frac(0.80)
View(PANGEA_observations_training) #3282 observations

#filter to just our RSR genes
#bring down the PANGEA dataframe size
PANGEA_de_training_RSRonly<-PANGEA_all %>%
  filter(X1 %in% RSRgenes$Gene) %>%
  pivot_longer(-X1, names_to = "Drug_CellLine", values_to = "DE_Value") %>%
  filter(Drug_CellLine %in% PANGEA_observations_training$Observation_Full) %>%
  #pivot_wider(names_from = "Drug_CellLine", values_from = "DE_Value") %>% #exclude this pivot
  select(Gene = X1, everything())
View(PANGEA_de_training_RSRonly)

#McGrail RSR
RSRSignatureGenes<-read_tsv(here("data","RNA_Signatures", "McGrailRSR_Genes_Coefficients.tsv")) %>%
  arrange(Gene)
View(RSRSignatureGenes)

#run correlations to McGrail RSR
PANGEA_de_training_RSRonly_McGrail<-PANGEA_de_training_RSRonly %>%
  filter(Gene %in% RSRSignatureGenes$Gene)
View(PANGEA_de_training_RSRonly_McGrail)
#then join with coefficients, and re-format

JoinedForCorrelationCalculation<-left_join(PANGEA_de_training_RSRonly_McGrail, RSRSignatureGenes)
View(JoinedForCorrelationCalculation)

PANGEA_McGrailRSR<-JoinedForCorrelationCalculation %>%
  group_by(Drug_CellLine)%>%
  summarize(McGrailRSR_Corr = cor(DE_Value, Coefficient ))
View(PANGEA_McGrailRSR)

PANGEA_McGrailRSR_ZScore<-PANGEA_McGrailRSR%>%
  ungroup() %>%
  mutate(Mean = mean(McGrailRSR_Corr), 
            SD = sd(McGrailRSR_Corr), 
         McGrailRSR_Z_Score = (McGrailRSR_Corr - Mean)/ SD) %>%
  select(Drug_CellLine, McGrailRSR_Corr, McGrailRSR_Z_Score)
View(PANGEA_McGrailRSR_ZScore)

#clean up output and print
PANGEA_McGrailRSR_Output<-PANGEA_McGrailRSR_ZScore %>%
  separate(Drug_CellLine, sep = "_", into = c("Drug", "Dose", "Time", "Cell_Line"),
           remove = FALSE) 
View(PANGEA_McGrailRSR_Output)
```

Add PARPness

```{r}
#05/16/21
#add mcgrail parpness
PARPSignatureGenes<-read_tsv(here("data","RNA_Signatures", "McGrailPARPness_Genes_Coefficients.tsv")) %>%
  arrange(Gene)
View(PARPSignatureGenes) #147 genes

#run correlations to McGrail RSR
PANGEA_de_training_PARPonly_McGrail<-PANGEA_de_training_RSRonly %>%
  filter(Gene %in% PARPSignatureGenes$Gene)
View(PANGEA_de_training_PARPonly_McGrail)
#then join with coefficients, and re-format

JoinedForCorrelationCalculation<-left_join(PANGEA_de_training_PARPonly_McGrail, PARPSignatureGenes)
View(JoinedForCorrelationCalculation)

PANGEA_McGrailPARP<-JoinedForCorrelationCalculation %>%
  group_by(Drug_CellLine)%>%
  summarize(McGrailPARP_Corr = cor(DE_Value, Coefficient ))
View(PANGEA_McGrailPARP)

PANGEA_McGrailPARP_ZScore<-PANGEA_McGrailPARP%>%
  ungroup() %>%
  mutate(Mean = mean(McGrailPARP_Corr), 
            SD = sd(McGrailPARP_Corr), 
         McGrailPARP_Z_Score = (McGrailPARP_Corr - Mean)/ SD) %>%
  select(Drug_CellLine, McGrailPARP_Corr, McGrailPARP_Z_Score)
View(PANGEA_McGrailPARP_ZScore)

#clean up output and print
PANGEA_McGrailPARP_Output<-PANGEA_McGrailPARP_ZScore %>%
  separate(Drug_CellLine, sep = "_", into = c("Drug", "Dose", "Time", "Cell_Line"),
           remove = FALSE) 
View(PANGEA_McGrailPARP_Output)

#clean up for OUTPUT file
#join with RSR file, join with drug library file
View(drugLibrary)
PANGEA_JoinBoth<-left_join(PANGEA_McGrailPARP_Output, PANGEA_McGrailRSR_Output) 
PANGEA_JoinBoth_Drug<-left_join(PANGEA_JoinBoth, drugLibrary) %>%
  select(Drug_CellLine, Drug, Cell_Line, Dose, Time, 
         McGrailRSR_Corr, McGrailRSR_Z_Score,
         McGrailPARP_Corr, McGrailPARP_Z_Score, 
         class, pathway, target, fda,Cmap_clinical)
View(PANGEA_JoinBoth_Drug)
#write to file
write_csv(PANGEA_JoinBoth_Drug, here("output", "MinePerturbed_PANGEA", "PANGEA_MineRSR_PARPness.csv"))


#plots
#RAR full distribution raw correlation scores
plotRSR_RawCorr<- PANGEA_JoinBoth_Drug%>%
  arrange(desc(McGrailRSR_Corr)) %>%
  ggplot(aes(x=reorder(Drug_CellLine, -McGrailRSR_Corr), y=McGrailRSR_Corr)) +
  geom_bar(stat="identity",  aes(fill=Cell_Line))   
plotRSR_RawCorr<-plotRSR_RawCorr + labs(title = "Distribution of McGrail RSR Correlations ", subtitle = "PANGEA (80%)") +
  xlab("") +
  ylab("Correlation") + 
  guides(fill=guide_legend(title="Cell Line")) + 
  theme(#axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.title.x=element_blank(),
        axis.ticks.x =element_blank(),
        axis.text.x=element_blank())  
plotRSR_RawCorr

#McGrail barplot drug X cell lines over 2.0
#with and without facet
plotRSR_byCellLine<- PANGEA_JoinBoth_Drug%>%
  arrange(desc(McGrailRSR_Z_Score)) %>%
  filter(McGrailRSR_Z_Score >=2.0) %>%
  ggplot(aes(x=reorder(Drug_CellLine, -McGrailRSR_Z_Score), y=McGrailRSR_Z_Score)) +
  geom_bar(stat="identity", aes(fill=Cell_Line))   
plotRSR_byCellLine<-plotRSR_byCellLine + labs(title = "Distribution of McGrail RSR Z-Scores > 2.0 ", subtitle = "PANGEA (80%)") +
  xlab("") +
  ylab("Z-Score") + 
  guides(fill=guide_legend(title="Cell Line")) + 
  theme(#axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.title.x=element_blank(),
        axis.ticks.x =element_blank(),
        axis.text.x=element_blank())  +
  facet_wrap(~Cell_Line)
plotRSR_byCellLine

#by class
plotRSR_byClass<- PANGEA_JoinBoth_Drug%>%
  arrange(desc(McGrailRSR_Z_Score)) %>%
  filter(McGrailRSR_Z_Score >=2.0) %>%
  ggplot(aes(x=reorder(Drug_CellLine, -McGrailRSR_Z_Score), y=McGrailRSR_Z_Score)) +
  geom_bar(stat="identity", aes(fill=class))   
plotRSR_byClass<-plotRSR_byClass + labs(title = "Distribution of McGrail RSR Z-Scores > 2.0 ", subtitle = "PANGEA (80%)") +
  xlab("") +
  ylab("Z-Score") + 
  guides(fill=guide_legend(title="Cell Line")) + 
  theme(#axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.title.x=element_blank(),
        axis.ticks.x =element_blank(),
        axis.text.x=element_blank())  +
  facet_wrap(~class)
plotRSR_byClass
ggsave(here("output", "MinePerturbed_PANGEA", "PANGEA_McGrailRSR_TopHits_ByDrugClass.png"), width = 26, height = 20, units = c("cm"), dpi = 300)


#PARPness full distribution raw correlation scores
plotPARP_RawCorr<- PANGEA_JoinBoth_Drug%>%
  arrange(desc(McGrailPARP_Corr)) %>%
  ggplot(aes(x=reorder(Drug_CellLine, -McGrailPARP_Corr), y=McGrailPARP_Corr)) +
  geom_bar(stat="identity",  aes(fill=Cell_Line))   
plotPARP_RawCorr<-plotPARP_RawCorr + labs(title = "Distribution of McGrail PARPness Correlations ", subtitle = "PANGEA (80%)") +
  xlab("") +
  ylab("Correlation") + 
  guides(fill=guide_legend(title="Cell Line")) + 
  theme(#axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.title.x=element_blank(),
        axis.ticks.x =element_blank(),
        axis.text.x=element_blank())  
plotPARP_RawCorr

#PARPness Z-Score >2.0 only
plotPARP_byCellLine<- PANGEA_JoinBoth_Drug%>%
  arrange(desc(McGrailPARP_Z_Score)) %>%
  filter(McGrailPARP_Z_Score >=2.0) %>%
  ggplot(aes(x=reorder(Drug_CellLine, -McGrailPARP_Z_Score), y=McGrailPARP_Z_Score)) +
  geom_bar(stat="identity",  aes(fill=Cell_Line))   
plotPARP_byCellLine<-plotPARP_byCellLine + labs(title = "Distribution of McGrail PARPness Z-Scores > 2.0 ", subtitle = "PANGEA (80%)") +
  xlab("") +
  ylab("Z-Score") + 
  guides(fill=guide_legend(title="Cell Line")) + 
  theme(#axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.title.x=element_blank(),
        axis.ticks.x =element_blank(),
        axis.text.x=element_blank())  +
  facet_wrap(~Cell_Line)
plotPARP_byCellLine
ggsave(here("output", "MinePerturbed_PANGEA", "PANGEA_McGrailPARPness_TopHits_ByCellLine.png"), width = 26, height = 20, units = c("cm"), dpi = 300)

#by class
plotPARP_byDrugClass<- PANGEA_JoinBoth_Drug%>%
  arrange(desc(McGrailPARP_Z_Score)) %>%
  filter(McGrailPARP_Z_Score >=2.0) %>%
  ggplot(aes(x=reorder(Drug_CellLine, -McGrailPARP_Z_Score), y=McGrailPARP_Z_Score)) +
  geom_bar(stat="identity", aes(fill=class)) #aes(fill=Cell_Line))   
plotPARP_byDrugClass<-plotPARP_byDrugClass + labs(title = "Distribution of McGrail PARPness Z-Scores > 2.0 ", subtitle = "PANGEA (80%)") +
  xlab("") +
  ylab("Z-Score") + 
  guides(fill=guide_legend(title="Cell Line")) + 
  theme(#axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.title.x=element_blank(),
        axis.ticks.x =element_blank(),
        axis.text.x=element_blank())  +
  facet_wrap(~class)
plotPARP_byDrugClass
ggsave(here("output", "MinePerturbed_PANGEA", "PANGEA_McGrailPARPness_TopHits_ByDrugClass.png"), width = 26, height = 20, units = c("cm"), dpi = 300)

```

```{r}
library(ggpubr)
#scatter plot of RSR versus PARPness
plotRSRvPARP<- PANGEA_JoinBoth_Drug%>%
  ggplot(aes(x=McGrailPARP_Z_Score, y=McGrailPARP_Z_Score)) +
  geom_point()   
plotRSRvPARP


plotRSRvPARP<-ggscatter(PANGEA_JoinBoth_Drug, x = "McGrailPARP_Z_Score", y = "McGrailRSR_Z_Score",
   color = "black",fill="black", shape = 21, size = 1.5,, # Points color, shape and size
   add = "reg.line",  # Add regressin line
   add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
   conf.int = TRUE, # Add confidence interval
   cor.coef = TRUE, # Add correlation coefficient. see ?stat_cor
   cor.coeff.args = list(method = "spearman", label.x = 3, label.sep = "\n"),
   title="Correlation of McGrail RSR and McGrail PARPness Z-Scores",
   subtitle="for PANGEA Perturbation Set"
   )
plotRSRvPARP

#then zoom in
#require in the top RSR or the top PARPness
PANGEA_JoinBoth_Drug_top<-PANGEA_JoinBoth_Drug %>%
  filter(McGrailRSR_Z_Score>=2.0 | McGrailPARP_Z_Score>=2.0)
View(PANGEA_JoinBoth_Drug_top)

plotRSRvPARP<-ggscatter(PANGEA_JoinBoth_Drug, x = "McGrailPARP_Z_Score", y = "McGrailRSR_Z_Score",
   color = "black",fill="black", shape = 21, size = 1.5,, # Points color, shape and size
   add = "reg.line",  # Add regressin line
   add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
   conf.int = TRUE, # Add confidence interval
   cor.coef = TRUE, # Add correlation coefficient. see ?stat_cor
   cor.coeff.args = list(method = "spearman", label.x = 3, label.sep = "\n"),
   title="Correlation of McGrail RSR and McGrail PARPness Z-Scores",
   subtitle="for PANGEA Perturbation Set"
   )
plotRSRvPARP

```

```{r}
#add gsva


#summary file across all - ranking
#add sheets - for top RSR, top PARPness, top

##





```
