---
title: "RunRNASignatureMcGrailPARP"
author: "Aurora S Blucher"
date: "2/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(ggpubr)
```

## R Markdown

Separate script for McGrail PARPness signature. 

Notes
-04/04/21 Updated drug set with gemcitabine and AZD6738 typo fixed

```{r}
########################################################
#McGrail PARPness Signature
########################################################

#McGrail PARPness Signature
PARPnessSignatureGenes<-read_tsv(here("data","RNA_Signatures", "McGrailPARPness_Genes_Coefficients.tsv")) %>%
  arrange(Gene)
#View(PARPnessSignatureGenes)

#read in the intermediate file for CCLE/DepMap RNASeq
DepMap_TrainingLines_RNASeq<-read_tsv(here("data_intermediate", "CCLEDepMap_expression", "CCLEDepMap_TrainingLines_RNASeq_LONG.tsv"))

#our training set
CCLE_Lines<-read_tsv(here("data", "CCLE_Training", "DepMap_forRepStress_BrEndoOvPanc_TRAINING_020221.tsv"))
#rsr drug list - mills lab compiled
RSR_drugs<-read_csv(here("data", "Drugs", "RSR_PARPness_DrugsOfInterest.csv"))


#Filter RNASeq data to McGrail PARPness
DepMap_RNASeq_PARPnessGenes_cleaned<-DepMap_TrainingLines_RNASeq  %>%
  filter(Gene %in% PARPnessSignatureGenes$Gene) 
dim(DepMap_RNASeq_PARPnessGenes_cleaned)
#View(DepMap_RNASeq_PARPnessGenes_cleaned)
#View(unique(DepMap_RNASeq_PARPnessGenes_cleaned$Name)) #127

#Run full correelations

#first, filter the RSR gene set to what was found in DepMap/ CCLE RNA-seq
PARPnessSignatureGenes_filtered<-PARPnessSignatureGenes %>%
  filter(Gene %in% DepMap_RNASeq_PARPnessGenes_cleaned$Gene)
#View(PARPnessSignatureGenes_filtered)

#re-structure, then run against corelation of RSR
DepMap_RNASeq_PARPnessGenes_cleaned_dataframe<-DepMap_RNASeq_PARPnessGenes_cleaned %>%
  select(DepMapID = DepMap_ID, Gene, Log2_TPM ) %>%
  arrange(Gene) 
#View(DepMap_RNASeq_PARPnessGenes_cleaned_dataframe)

#join with our gene co-efficients  
Joined_DepMapRNASeq_PARPnessCoefficients<-left_join(DepMap_RNASeq_PARPnessGenes_cleaned_dataframe,PARPnessSignatureGenes_filtered )
#View(Joined_DepMapRNASeq_PARPnessCoefficients)

class(Joined_DepMapRNASeq_PARPnessCoefficients$Log2_TPM)#numeric
class(Joined_DepMapRNASeq_PARPnessCoefficients$Coefficient)#character -> convert to numeric

#run correlations
dataFrame_PARPnesscorr<-Joined_DepMapRNASeq_PARPnessCoefficients %>%
  group_by(DepMapID) %>%
  summarize(correlation = cor(Log2_TPM, Coefficient )) 
View(dataFrame_PARPnesscorr)
#intermediate output correlations; these can go in the intermediate files
#write_tsv(dataFrame_PARPnesscorr, here("data_intermediate", "McGrail_PARPness", "CCLEDepMap_TrainingLines_McGrailPARPness.tsv"))


#join with cell line information (cancer type)
#boxplot of correlations, facet by disease
joinPARPnessCorr_CellLineInfo<-left_join(dataFrame_PARPnesscorr, CCLE_Lines) %>%
  select(DepMapID, correlation, CellLine_Name_Cleaned, Cancer_Type)
#View(joinPARPnessCorr_CellLineInfo)

#boxplot
boxplot_PARPnesscellLines <- ggboxplot(joinPARPnessCorr_CellLineInfo, x = "Cancer_Type", y = "correlation",
      color = "Cancer_Type")
ggpar(boxplot_PARPnesscellLines, main = "", submain = "",
      #scatter_test, main = "MDAMB175VII (ACH-000759)", submain = "Breast",
      
      ylab = "Corr with PARPness Signature", 
      font.x = 10, font.y = 10)
#boxplot_cellLines
```
```{r}
#McGrail PARPness Correlation - Example Cell Lines; Best and Worst Scores
###ACH-000831 r = 0.80 , lowest: ACH-001145 r = `0.34

#EXAMPLE 1 - HIGH SCORE
testCase<-Joined_DepMapRNASeq_PARPnessCoefficients%>%
  select(DepMapID, Gene, Log2_TPM) %>%
  arrange(Gene) %>%
  filter(DepMapID =="ACH-000831") 

#join with the correlation coefficients; so we can have 1 data frame
joinFrame<-left_join(testCase, PARPnessSignatureGenes_filtered)
#View(joinFrame)

#run correlation
#testCor<-cor(testCase$Log2_TPM, RSRSignatureGenes_filtered$Coefficient)
#testCor
PARPnessSignatureGenes_filtered$Coefficient<-as.numeric(PARPnessSignatureGenes_filtered$Coefficient)
joinFrame$Coefficient<-as.numeric(joinFrame$Coefficient)

#test scatter of individual cell line genes
scatter_test<-joinFrame %>%
  ggscatter(x = "Coefficient", y = "Log2_TPM", 
            add = "reg.line",  
            add.params = list(color = "dodgerblue2", fill = "lightgray"),
            conf.int = FALSE) + 
  stat_cor(method = "pearson",color = "dodgerblue2",label.x=0, label.y = 10)
ggpar(scatter_test,  main = "HEC50B (ACH-000831)", submain = "Endometrial", #best ~0.80
      xlab = "McGrail PARPness Gene Signature - Coefficient", ylab = "Log2_TPM")

#EXAMPLE 2 LOW SCORE
testCase2<-Joined_DepMapRNASeq_PARPnessCoefficients%>%
  select(DepMapID, Gene, Log2_TPM) %>%
  arrange(Gene) %>%
  filter(DepMapID =="ACH-000759") 

#join with the correlation coefficients; so we can have 1 data frame
joinFrame2<-left_join(testCase2, PARPnessSignatureGenes_filtered)
#View(joinFrame2)

scatter_test<-joinFrame2 %>%
  ggscatter(x = "Coefficient", y = "Log2_TPM", 
            add = "reg.line",  
            add.params = list(color = "dodgerblue2", fill = "lightgray"),
            conf.int = FALSE) + 
  stat_cor(method = "pearson",color = "dodgerblue2", label.x=0, label.y = 10)
ggpar(scatter_test, main = "MDAMB175VII (ACH-000759)", submain = "Ovarian",
      xlab = "McGrail PARPness Gene Signature - Coefficient", ylab = "Log2_TPM")
```

```{r}
#######MCGRAIL PARPNESS VS DRUG AUC
#read in GDSC drug info
GDSC_drugs_filtered<-read_tsv(here("data_intermediate", "GDSCv2", "CCLEDepMap_TrainingLInes_GDSCv2_RSRDrugs_040421.tsv"))

#join our cell line/ correlations data frame with drugs
#try just LEFT join, so we can keep it all in LONG Format, need to nest
joinPARPnessCorr_CellLineInfo_wDrug<-left_join(joinPARPnessCorr_CellLineInfo, GDSC_drugs_filtered)%>%
    filter(DRUG_NAME!="NA")#if no drug data then remove for that line
#View(joinPARPnessCorr_CellLineInfo_wDrug)

#join with nice drug/class compound name for our plots
RSR_drugs_namesOnly<-RSR_drugs %>% select(DrugName_Class, DRUG_ID = GDSC2_ID, Class)
joinPARPnessCorr_CellLineInfo_wDrug_Names<-left_join(joinPARPnessCorr_CellLineInfo_wDrug, RSR_drugs_namesOnly) %>%
  arrange(Class)
#View(joinPARPnessCorr_CellLineInfo_wDrug_Names)
#test -> can we facet by drug?

#SCATTER PLOT, with correlatons
scatter_drugAUC<-joinPARPnessCorr_CellLineInfo_wDrug_Names %>%
  ggscatter(x = "correlation", y = "AUC_PUBLISHED", #color="Cancer_Type",
            add = "reg.line",  
            add.params = list(color = "dodgerblue2", fill = "lightgray"),
            conf.int = FALSE, title = "Correlation of McGrail PARPness Score and Drug AUC", subtitle = "Breast/Ov/Endo/Pancr Lines",
            xlab = "PARPness Score", ylab = "Drug AUC") + 
  stat_cor(method = "pearson",color = "dodgerblue2", size = 2.5, label.x=0.2, label.y = 0.35)
facet(scatter_drugAUC, facet.by = "DrugName_Class")
```

```{r}
#then split for each cancer type
#BREAST SCATTER PLOT, with correlatons
scatter_drugAUC<-joinPARPnessCorr_CellLineInfo_wDrug_Names %>%
  filter(Cancer_Type=="Breast Cancer") %>%
  ggscatter(x = "correlation", y = "AUC_PUBLISHED", color="olivedrab3",
            add = "reg.line",  
            add.params = list(color = "dodgerblue2", fill = "lightgray"),
            conf.int = FALSE, title = "Correlation of McGrail PARPness Score and Drug AUC", subtitle = "Breast Only",
            xlab = "PARPness Score", ylab = "Drug AUC") + 
  stat_cor(method = "pearson",color = "dodgerblue2", size = 2.5, label.x=0.2, label.y = 0.35)
facet(scatter_drugAUC, facet.by = "DrugName_Class")
```

```{r}
#OV SCATTER PLOT, with correlatons
scatter_drugAUC_ov<-joinPARPnessCorr_CellLineInfo_wDrug_Names %>%
  filter(Cancer_Type=="Ovarian Cancer") %>%
  ggscatter(x = "correlation", y = "AUC_PUBLISHED", color="tomato1",
            add = "reg.line",  
            add.params = list(color = "dodgerblue2", fill = "lightgray"),
            conf.int = FALSE, title = "Correlation of McGrail PARPness Score and Drug AUC", subtitle = "Ovarian Only",
            xlab = "PARPness Score", ylab = "Drug AUC") + 
  stat_cor(method = "pearson",color = "dodgerblue2", size = 2.5, label.x=0.4, label.y = 0.35)
facet(scatter_drugAUC_ov, facet.by = "DrugName_Class")
```

```{r}
#ENDO SCATTER PLOT, with correlatons
scatter_drugAUC_endo<-joinPARPnessCorr_CellLineInfo_wDrug_Names %>%
  filter(Cancer_Type=="Endometrial/Uterine Cancer") %>%
  ggscatter(x = "correlation", y = "AUC_PUBLISHED", color="darkorchid1",
            add = "reg.line",  
            add.params = list(color = "dodgerblue2", fill = "lightgray"),
            conf.int = FALSE, title = "Correlation of McGrail PARPnessScore and Drug AUC", subtitle = "Endometrial Only",
            xlab = "PARPness Score", ylab = "Drug AUC") + 
  stat_cor(method = "pearson",color = "dodgerblue2", size = 2.5, label.x=0.6, label.y = 0.34)
facet(scatter_drugAUC_endo, facet.by = "DrugName_Class")
```

```{r}
#PANC SCATTER PLOT, with correlatons
scatter_drugAUC_panc<-joinPARPnessCorr_CellLineInfo_wDrug_Names %>%
  filter(Cancer_Type=="Pancreatic Cancer") %>%
  ggscatter(x = "correlation", y = "AUC_PUBLISHED", color="turquoise",
            add = "reg.line",  
            add.params = list(color = "dodgerblue2", fill = "lightgray"),
            conf.int = FALSE, title = "Correlation of McGrail PARPness Score and Drug AUC", subtitle = "Pancreatic Only",
            xlab = "PARPness Score", ylab = "Drug AUC") + 
  stat_cor(method = "pearson",color = "dodgerblue2", size = 2.5, label.x=0.4, label.y = 0.35)
facet(scatter_drugAUC_panc, facet.by = "DrugName_Class")


```